spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    #        show_sql: true
    #        format_sql: true
    #        use_sql_comments: true
    open-in-view: on
decorator:
  datasource:
    # p6spy ?? ??
    p6spy:
      enable-logging: true

#      multiline: true
#      logging: slf4j

